=== julenferre/sza16-3/XML/erabiltzaileak.dtd
<!ELEMENT erabiltzaileak (erabiltzailea)*>
	<!ATTLIST erabiltzaileak azkenid IDREF #REQUIRED>
<!ELEMENT erabiltzailea (izena, abizenak, eposta, pasahitza, irudia)>
	<!ATTLIST erabiltzailea id ID #REQUIRED>
	<!ELEMENT izena (#PCDATA)>
	<!ELEMENT abizenak (#PCDATA)>
	<!ELEMENT eposta (#PCDATA)>
	<!ELEMENT pasahitza (#PCDATA)>
	<!ELEMENT irudia (#PCDATA)>

=== julenferre/sza16-3/XML/erabiltzaileak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bisitak SYSTEM "erabiltzaileak.dtd">
<erabiltzaileak azkenid="b11">
<erabiltzailea id="b1"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654132</pasahitza><argazkia/></erabiltzailea><erabiltzailea id="b2"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b3"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b4"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b5"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b6"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b7"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b8"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>321654987</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b9"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>6157463514</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b10"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>96532741632751</pasahitza><argazkia>selfiee</argazkia></erabiltzailea><erabiltzailea id="b11"><izena/><abizenak>Trump Elizondo</abizenak><eposta>dtrump420@ikasle.ehu.eus</eposta><pasahitza>6457263517</pasahitza><argazkia>selfiee</argazkia></erabiltzailea></erabiltzaileak>
